### ISSUE TITLE
Create Releases

### ISSUE THREAD

**Issue by Nosferican** [haberdashPI/vscode-R-in-julia#1]
It would be great to have the releases tags created so people may install it through `vsix` when using non Microsoft products.

**Comment by haberdashPI** [comment]
Ah, I didn't know about that. Happy to to do that.

Do you have any guidance on how to automate the process? I'm assuming there's a simple github Action or something for vscode extensions releases on github. It would be nice to do this for all my extensions.

**Comment by Nosferican** [comment]
@davidanthoff, could you share the steps for an extension to provide the `.vsix` release asset?

**Comment by davidanthoff** [comment]
We have a very involved Azure Pipelines script that does everything for us. The deploy to github stage is [here](https://github.com/julia-vscode/julia-vscode/blob/master/azure-pipelines.yml#L319).
